<x-layouts.app title="Executive Dashboard">
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">{{ now()->format('l, d F Y') }}</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">Good day, {{ strtok(session('user_name'), ' ') }}.</h2><p class="mt-1 text-sm text-slate-500">Here is the live operating position across your retail business.</p></div><a href="{{ route('reports.index') }}" class="btn-secondary">View detailed reports <span>→</span></a></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Today’s Sales', $todaySales, 'Rp', 'bg-indigo-50 text-indigo-600', '▣'], ['Transactions', $transactions, '', 'bg-sky-50 text-sky-600', '◫'], ['Gross Profit', $profit, 'Rp', 'bg-emerald-50 text-emerald-600', '↗'], ['Cash Position', $cashPosition, 'Rp', 'bg-amber-50 text-amber-600', '◴']] as [$label, $value, $prefix, $color, $icon])
        <div class="card p-5"><div class="flex items-start justify-between"><div><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-900">{{ $prefix }}{{ in_array($label, ['Transactions']) ? number_format($value) : number_format($value, 0, ',', '.') }}</p></div><span class="metric-icon {{ $color }}">{{ $icon }}</span></div><p class="mt-3 text-xs text-slate-500">Live data from completed transactions</p></div>
        @endforeach
    </div>
    <div class="mt-4 grid gap-4 sm:grid-cols-2"><div class="card border-amber-200 bg-amber-50/40 p-5"><p class="text-sm font-semibold text-amber-800">Low stock attention</p><p class="mt-1 text-2xl font-bold text-amber-900">{{ $lowStock }} products</p><a href="{{ route('inventory.index') }}" class="mt-3 inline-block text-sm font-bold text-amber-800 hover:text-amber-900">Review inventory →</a></div><div class="card border-indigo-200 bg-indigo-50/40 p-5"><p class="text-sm font-semibold text-indigo-800">Open purchasing workflow</p><p class="mt-1 text-2xl font-bold text-indigo-900">{{ $pendingPurchases }} purchase orders</p><a href="{{ route('purchases.index') }}" class="mt-3 inline-block text-sm font-bold text-indigo-800 hover:text-indigo-900">Manage receiving →</a></div></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-5"><section class="card xl:col-span-3"><div class="card-header"><div><h3 class="font-bold text-slate-900">Sales movement</h3><p class="text-sm text-slate-500">Last seven days, completed sales</p></div><span class="badge badge-info">IDR</span></div><div class="h-72 px-5 py-5"><div class="flex h-full items-end gap-3">@php($max = max(1, $dailySales->max('total') ?? 1)) @forelse($dailySales as $day)<div class="group flex flex-1 flex-col justify-end"><div title="Rp{{ number_format($day->total, 0, ',', '.') }}" class="min-h-2 rounded-t-md bg-indigo-500 transition group-hover:bg-indigo-700" style="height: {{ max(6, ($day->total / $max) * 92) }}%"></div><p class="mt-2 text-center text-[10px] font-medium text-slate-400">{{ \Carbon\Carbon::parse($day->date)->format('D') }}</p></div>@empty<div class="flex h-full w-full items-center justify-center text-sm text-slate-400">Sales data will appear after transactions are completed.</div>@endforelse</div></div></section>
        <section class="card xl:col-span-2"><div class="card-header"><div><h3 class="font-bold text-slate-900">Top products</h3><p class="text-sm text-slate-500">By sales revenue</p></div></div><div class="divide-y divide-slate-100">@forelse($topProducts as $product)<div class="flex items-center justify-between px-5 py-3"><div><p class="text-sm font-semibold text-slate-800">{{ $product->product_name }}</p><p class="text-xs text-slate-500">{{ number_format($product->quantity, 0, ',', '.') }} units sold</p></div><p class="text-sm font-bold text-slate-900">Rp{{ number_format($product->revenue, 0, ',', '.') }}</p></div>@empty<div class="p-8 text-center text-sm text-slate-400">No completed sales yet.</div>@endforelse</div></section>
    </div>
    <section class="card mt-6"><div class="card-header"><div><h3 class="font-bold text-slate-900">Recent sales</h3><p class="text-sm text-slate-500">Latest completed invoices across outlets</p></div><a class="text-sm font-bold text-indigo-600 hover:text-indigo-700" href="{{ route('reports.index') }}">Open reports →</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Cashier</th><th>Time</th><th>Status</th><th class="text-right">Total</th></tr></thead><tbody>@forelse($recentSales as $sale)<tr><td class="font-semibold text-indigo-700"><a href="{{ route('sales.receipt', $sale->id) }}">{{ $sale->invoice_number }}</a></td><td>{{ $sale->cashier_name }}</td><td>{{ \Carbon\Carbon::parse($sale->sold_at)->format('d M, H:i') }}</td><td><span class="badge badge-success">Completed</span></td><td class="text-right font-bold text-slate-900">Rp{{ number_format($sale->grand_total, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-400">No sales have been completed. Open the POS to process the first transaction.</td></tr>@endforelse</tbody></table></div></section>
</x-layouts.app>
