<x-layouts.app title="Administration">
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Configuration, access control, and protected system history.</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Administration</h2></div><div class="flex flex-wrap gap-2"><a href="{{ route('administration.index','settings') }}" class="btn-secondary px-3 py-2 text-xs">Settings</a><a href="{{ route('administration.index','users') }}" class="btn-secondary px-3 py-2 text-xs">Users</a><a href="{{ route('administration.index','roles') }}" class="btn-secondary px-3 py-2 text-xs">Roles</a><a href="{{ route('administration.index','audit') }}" class="btn-secondary px-3 py-2 text-xs">Audit log</a></div></div>
@if($section === 'settings')
<section class="card max-w-3xl"><div class="card-header"><div><h3 class="font-bold text-slate-900">System settings</h3><p class="text-sm text-slate-500">Business and POS policies are stored server-side.</p></div></div><form method="POST" action="{{ route('administration.settings.update') }}" class="grid gap-5 p-5 md:grid-cols-2">@csrf @method('PUT')<div><label class="field-label">Company display name</label><input name="company_name" required class="w-full px-3 py-2" value="{{ $records->firstWhere('key','company_name')->value ?? 'AksiSoft Retail Indonesia' }}"></div><div><label class="field-label">Tax rate (%)</label><input name="tax_rate" required type="number" min="0" max="100" step="0.01" class="w-full px-3 py-2" value="{{ $records->firstWhere('key','tax_rate')->value ?? 0 }}"></div><label class="md:col-span-2 flex items-center gap-3 rounded-lg bg-slate-50 p-4 text-sm font-medium text-slate-700"><input type="checkbox" name="allow_negative_stock" value="1" {{ ($records->firstWhere('key','allow_negative_stock')->value ?? false) ? 'checked' : '' }}>Allow negative stock only when approved by policy</label><div class="md:col-span-2"><button class="btn-primary">Save settings</button></div></form></section>
@elseif($section === 'users')
<section class="card"><div class="card-header"><div><h3 class="font-bold text-slate-900">Users and assignment</h3><p class="text-sm text-slate-500">Roles are a baseline; granular permission checks protect sensitive mutations.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Username</th><th>Role</th><th>Last login</th><th>Status</th></tr></thead><tbody>@forelse($records as $user)<tr><td><p class="font-semibold">{{ $user->name }}</p><p class="text-xs text-slate-500">{{ $user->email }}</p></td><td>{{ $user->username }}</td><td><span class="badge badge-info">{{ $user->role_name ?? 'No role' }}</span></td><td>{{ $user->last_login_at ? \Carbon\Carbon::parse($user->last_login_at)->format('d M Y H:i') : 'Never' }}</td><td><span class="badge {{ $user->status === 'active' ? 'badge-success' : 'badge-danger' }}">{{ ucfirst($user->status) }}</span></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-400">No users found.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-3">{{ $records->links() }}</div></section>
@elseif($section === 'roles')
<section class="card"><div class="card-header"><div><h3 class="font-bold text-slate-900">Role-based access control</h3><p class="text-sm text-slate-500">Seeded roles are paired with granular permissions.</p></div></div><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">@foreach($records as $role)<div class="rounded-xl border border-slate-200 p-4"><p class="font-bold text-slate-900">{{ $role->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $role->description }}</p><p class="mt-4 text-xs font-semibold uppercase tracking-wide text-indigo-600">{{ $role->slug }}</p></div>@endforeach</div></section><section class="card mt-6"><div class="card-header"><h3 class="font-bold text-slate-900">Permission catalogue</h3></div><div class="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-3">@foreach($permissions as $permission)<div class="rounded-lg bg-slate-50 px-3 py-2"><p class="text-sm font-semibold text-slate-800">{{ $permission->slug }}</p><p class="text-xs text-slate-500">{{ $permission->module }}</p></div>@endforeach</div></section>
@else
<section class="card"><div class="card-header"><div><h3 class="font-bold text-slate-900">Protected audit log</h3><p class="text-sm text-slate-500">Important writes, authentication events, and inventory operations are recorded.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Module</th><th>Record</th><th>Network</th></tr></thead><tbody>@forelse($records as $log)<tr><td>{{ \Carbon\Carbon::parse($log->created_at)->format('d M Y H:i:s') }}</td><td>{{ $log->user_name ?? 'System / anonymous' }}</td><td><span class="badge badge-info">{{ str_replace('_',' ',ucfirst($log->action)) }}</span></td><td>{{ ucfirst($log->module) }}</td><td>{{ $log->record_type ? $log->record_type.' #'.$log->record_id : '—' }}</td><td class="text-xs text-slate-500">{{ $log->ip_address ?? '—' }}</td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-slate-400">No audit events are available.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-3">{{ $records->links() }}</div></section>
@endif
</x-layouts.app>
