<x-layouts.app :title="$type === 'customer' ? 'Customers' : 'Suppliers'">
@php($isCustomer = $type === 'customer')
<div class="mb-6"><p class="text-sm text-slate-500">{{ $isCustomer ? 'Customer profiles, groups, and balances' : 'Vendor profiles and purchasing contacts' }}</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $isCustomer ? 'Customer management' : 'Supplier management' }}</h2></div>
<section class="card mb-6"><div class="card-header"><div><h3 class="font-bold text-slate-900">Add {{ $isCustomer ? 'customer' : 'supplier' }}</h3><p class="text-sm text-slate-500">Captured data is available during {{ $isCustomer ? 'checkout' : 'purchase ordering' }}.</p></div></div><form method="POST" action="{{ $isCustomer ? route('customers.store') : route('suppliers.store') }}" class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">@csrf
@if($isCustomer)<div><label class="field-label">Customer name</label><input name="name" required class="w-full px-3 py-2"></div><div><label class="field-label">Phone</label><input name="phone" class="w-full px-3 py-2"></div><div><label class="field-label">Email</label><input name="email" type="email" class="w-full px-3 py-2"></div><div><label class="field-label">Customer group</label><select name="customer_group_id" class="w-full px-3 py-2"><option value="">Walk-in / Retail</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</select></div><div class="xl:col-span-3"><label class="field-label">Address</label><input name="address" class="w-full px-3 py-2"></div>
@else<div><label class="field-label">Company name</label><input name="company_name" required class="w-full px-3 py-2"></div><div><label class="field-label">Contact person</label><input name="contact_person" class="w-full px-3 py-2"></div><div><label class="field-label">Phone</label><input name="phone" class="w-full px-3 py-2"></div><div><label class="field-label">Email</label><input name="email" type="email" class="w-full px-3 py-2"></div><div class="xl:col-span-2"><label class="field-label">Address</label><input name="address" class="w-full px-3 py-2"></div><div><label class="field-label">Payment terms</label><input name="payment_terms" placeholder="Net 30" class="w-full px-3 py-2"></div>
@endif<div class="flex items-end"><button class="btn-primary w-full">Save {{ $isCustomer ? 'customer' : 'supplier' }}</button></div></form></section>
<section class="card"><div class="card-header"><div><h3 class="font-bold text-slate-900">{{ $isCustomer ? 'Registered customers' : 'Active suppliers' }}</h3><p class="text-sm text-slate-500">{{ $records->total() }} records</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Code</th><th>{{ $isCustomer ? 'Customer' : 'Supplier' }}</th><th>Contact</th><th>{{ $isCustomer ? 'Balance / Points' : 'Terms' }}</th><th>Status</th></tr></thead><tbody>@forelse($records as $record)<tr><td class="font-semibold text-indigo-700">{{ $record->code }}</td><td><p class="font-semibold text-slate-900">{{ $isCustomer ? $record->name : $record->company_name }}</p><p class="text-xs text-slate-500">{{ $isCustomer ? ($record->address ?? 'No address') : ($record->contact_person ?? 'No contact person') }}</p></td><td><p>{{ $record->phone ?? '—' }}</p><p class="text-xs text-slate-500">{{ $record->email ?? '—' }}</p></td><td>{{ $isCustomer ? 'Rp'.number_format($record->outstanding_balance,0,',','.').' · '.$record->points.' pts' : ($record->payment_terms ?? '—') }}</td><td><span class="badge badge-success">{{ ucfirst($record->status) }}</span></td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-400">No records have been created.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-3">{{ $records->links() }}</div></section>
</x-layouts.app>
